services:
  api:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    ports:
      - 8080:8080
